### ISSUE TITLE
Consider using EXT4 rather than EXT2?

### ISSUE THREAD

**Issue by robinmarlow** [birdslikewires/openframe-linux#17]
Hi,

This is amazing work & has put a Joggler as a data logging device in a busy emergency department with chrome in kiosk mode.
However, in such a hostile environment the power does tend to get pulled unexpectedly.
I found this image was getting very upset with corruption on reboots until I converted the root to EXT4 (other equivalent file systems are available) - i was wondering if there was a particular reason you were sticking with EXT2 or if you'd consider changing it?

Or am I just doing something wrong & EXT2 should be fine!

Robin

**Comment by andydvsn** [comment]
Wow, that's amazing! I love hearing about how these things are being used. :)

So, the reason the image uses ext2 was to make it as friendly as possible to the hardware of those people writing the image to the internal memory, limiting the number of writes by not including journalling and (in theory) extending the life of that flash memory. 

That was the theory and I honestly don't know how accurate this really is, but because ext2 can be fairly easily converted in-place to ext4 (while the opposite is impossible) it seemed like a reasonable option to go with.

**Comment by robinmarlow** [comment]
Great, sounds like a sensible rationale.  You're right, it was easy to move
ext2-ext4

I might have been doing something wrong but I couldn't get a working kiosk
mode with chromium to fit in the internal memory so am running on a tiny
USB key stuck in the side.

I've been slightly eyeing tiny core linux (http://tinycorelinux.net/)
wondering if i'd be able to get an GUI to fit in the internal memory
(although a bit loathed to as I have a working solution at the moment!)
You must have managed this for the squeezeplayOS, so do you think I'm
making it unnecessarily complicated?

R

**Comment by andydvsn** [comment]
Ah, SqueezePlay OS has no underlying GUI. There's no desktop as such to fall back to, it's just SqueezePlay rendering to the screen with a basic window manager (matchbox, if I remember right).

It's definitely possible to do, but way easier using the extra space on a memory stick. :)
