### ISSUE TITLE
of-install missing from Bookworm

### ISSUE THREAD

**Issue by jimmygulp** [birdslikewires/openframe-linux#18]
Just wondering if there's a reason that of-install is currently missing from the Bookworm directory (/usr/local/sbin). The comments in Bullseye make mention of a copy to/from Bookworm but it's not there.

Just did a fresh install for my joggler using the pre-built image and ended up copying the script from the older version to get the install script. This worked fine and I've a happy Joggler running again!

**Comment by andydvsn** [comment]
What parts of of-install were you using? I hadn't tested any of that script on Bookworm and had assumed most things would be broken, so left it out.

Happy to fettle it back into action at some point, particularly if there are parts which are working!

**Comment by jimmygulp** [comment]
Just the generic bits to get a working display of jive / squeezeplay and whatever X server it's using:
./of-install squeezeplay

Worked without a problem for me and I've got a working joggler again. I had a very quick look through the script and couldn't see anything blindingly obvious that would be bookwork / bullseye specific.

**Comment by andydvsn** [comment]
Okay, I'm amazed SqueezePlay worked. :)

I'll test it out once I've fixed the build system (slight problem at the moment) and see if I can add it back.

**Comment by andydvsn** [comment]
Thought I'd closed this, but clearly not! The of-install script is back in Bookworm.

Not that it's necessarily the best way to install SqueezePlay these days; I believe the [currently preferred means](https://www.jogglerwiki.com/forum/viewtopic.php?f=2&t=5194) is to use jivelite and squeezelite, which separates the UI and the playback engine. This way OpenFrames can be controllers for other devices without being playback devices themselves, or can just control their own jivelite playback engine.

I no longer use the Squeezebox ecosystem, which is why none of my contributions have been updated in a long time. But my SqueezePlay repo and instructions are still [here](https://github.com/birdslikewires/squeezeplay) should anybody wish to tinker, and the "split implmentation" is cared for by [ralph-irving](https://github.com/ralph-irving).
